
# version: '3'
services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "5119:5119"
      - "8080:8080"
  #   networks:
  #     - db_network
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=starwars;User Id=sa;Password=GoEngineerProject123!;Trusted_Connection=False;Encrypt=False;"
  db:
    container_name: db
    build:
      context: database
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    # networks:
    #   - db_network
      
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

networks:
  db_network:

volumes:
  pgdata: {}


