services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: starshipped-db
    environment:
      SA_PASSWORD: GoEngineerProject123!
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/1.sql"

