// {"id":50,
// "swapiID":17,
// "url":"https://swapi.dev/api/starships/17/",
// "name":"Rebel transport",
// "model":"GR-75 medium transport",
// "manufacturer":"Gallofree Yards,
//  Inc.",
// "costInCredits":null,
// "length":"90",
// "maxAtmosphericSpeed":null,
// "crew":"6",
// "passengers":"90",
// "cargoCapacity":null,
// "consumables":"6 months",
// "hyprdriveRating":null,
// "mglt":"20",
// "starshipClass":null,
// "films":["https://swapi.dev/api/films/2/",
//     "https://swapi.dev/api/films/3/"],
// "pilots":[],
// "created":"2014-12-15T12:34:52.264000Z",
// "edited":"2014-12-20T21:23:49.895000Z"}
export interface Starship {
    name: string,
    id: number,
    model: string,
    manufacturer: string,
    pilots: string[]
}